### ISSUE TITLE
Add a manifest.json file

### ISSUE THREAD

**Issue by PaulRBerg** [sablierhq/safe-app#1]
As per the [docs](https://github.com/gnosis/safe-apps-sdk#testing-in-the-safe-multisig-application) provided by Gnosis:

> Once your app is ready you need to deploy it on the internet. It is mandatory that your app exposes a manifest.json file in the root dir.

Example structure:

```json
{
  "name": "YourAppName",
  "description": "A description of what your app do",
  "iconPath": "myAppIcon.svg"
}
```

**Comment by TomAFrench** [comment]
closed by #3

**Comment by PaulRBerg** [comment]
Was this really closed by #3? My understanding is that we still need a manifest.json file when going to production.

**Comment by TomAFrench** [comment]
Yeah I've added the required information to the manifest.json file here: https://github.com/sablierhq/safe-app/blob/develop/public/manifest.json

This is required so that the gnosis ui can display name/icon when adding this app. I've tested loading this app from the gnosis frontend and it automatically populates.

**Comment by PaulRBerg** [comment]
Oh I haven't looked into the `public` folder. Great.
